### ISSUE TITLE
make the new synchronizer work

### ISSUE THREAD

**Issue by kajatiger** [berlindiamonds/discourse-googledrive-backup#19]
we changed the synchronizer to be an instance method and created a base class for the drive_synchronizer and called the new class in the job. now all the tests are running green, but we need to make the backup work IRL and move the logic from the perform_method to the job, because now it is looping on two levels

**Comment by jenni** [comment]
The drive synchronizer uploads one file at a time and the Job is in charge of looping through the array of selected Backups.
