### ISSUE TITLE
define chunks

### ISSUE THREAD

**Issue by jenni** [berlindiamonds/discourse-googledrive-backup#22]
work on upload by chunks

**Comment by kajatiger** [comment]
I need help here. first of all: is the chunked upload really neccessary for google drive? or is it a specific problem for dropbox. second: what is the curser doing? third: do I need to pass all arguments (folder_name, filename, fullpath...)?

**Comment by jenni** [comment]
It's specific to Dropbox because of the limit of size per file they have for uploads, I didn't see any mention of that in google drive docs
