### ISSUE TITLE
Do a little spring cleanup

### ISSUE THREAD

**Issue by rstammer** [berlindiamonds/discourse-googledrive-backup#28]
Here's a sweet little yak to shave for in-between-time! :) I think it is good style common to many codebases to avoid unnecessary whitespace/trailing whitespace. So I'd recommend you to keep an eye on:

* https://github.com/berlindiamonds/discourse-googledrive-backup/blob/master/lib/drive_synchronizer.rb#L11

* https://github.com/berlindiamonds/discourse-googledrive-backup/blob/master/lib/drive_synchronizer.rb#L40

* https://github.com/berlindiamonds/discourse-googledrive-backup/blob/master/plugin.rb#L6

* https://github.com/berlindiamonds/discourse-googledrive-backup/blob/master/plugin.rb#L21

* https://github.com/berlindiamonds/discourse-googledrive-backup/blob/master/spec/drive_synchronizer_spec.rb#L1

* https://github.com/berlindiamonds/discourse-googledrive-backup/blob/master/spec/drive_synchronizer_spec.rb#L12

![bos_grunniens_at_yundrok_yumtso_lake](https://user-images.githubusercontent.com/3685123/28615181-7e78e1b0-71f8-11e7-8b32-c67f88983ee1.jpg)

**Comment by jenni** [comment]
Hey Robin thank you for looking into it! Actually, master is several commits behind the current plugin and I believe those spacing/trailing are past now, I'm a spacing/trailing maniac!
The new plugin code is located in the dev branch.

**Comment by kajatiger** [comment]
some of the white lines in the end where unneccesary and I deleted them now. But others actually have a meaning. For example gouping gems that one gem is depending on together and the main gem alone...
