### ISSUE TITLE
take care of the naming

### ISSUE THREAD

**Issue by kajatiger** [berlindiamonds/discourse-googledrive-backup#32]
make a decision about the name of the drive plugin as well as the base plugin in order to load them in the right order

**Comment by kajatiger** [comment]
eviltrouts suggestion:
discourse-sync-base
discourse-sync-googledrive
discourse-sync-dropbox
discourse-sync-etc…

**Comment by jenni** [comment]
Someone in Discourse has suggested:
[Discourse RGSoC](https://meta.discourse.org/t/rails-girls-summer-of-code-2017-backup-providers/65597/22)
```
discourse-sync-base
discourse-sync-to-amazon-glacier
discourse-sync-to-googledrive
…

```

As most probably there will be an amazon-something plugin too. I say +1 for that.
