### ISSUE TITLE
delete old backups

### ISSUE THREAD

**Issue by jenni** [berlindiamonds/discourse-googledrive-backup#35]
because google drive storage is not bottomless, we should take care of deleting old files

**Comment by kajatiger** [comment]
how? maybe not storing more than a certain quantity of backups and always throwing out the older ones?

**Comment by kajatiger** [comment]
checkout the remove branch

**Comment by kajatiger** [comment]
> So you will need to perform the following in the remove_old_files method:

    List all files on the remote folder

    Order this files by creation date

    Delete all files except the most N recent ones, where N is a plugin setting.

from falco

**Comment by kajatiger** [comment]
no matter what, the files don't get deleted from the drive account. I don't know why, I posted the question on [stackoverflow](https://stackoverflow.com/questions/45546974/delete-files-from-google-drive-service-account-with-the-google-drive-gem)
