### ISSUE TITLE
google drive plugin review

### ISSUE THREAD

**Issue by jenni** [berlindiamonds/discourse-googledrive-backup#43]
Hey @eviltrout,
we've worked together on the last touches of google drive backups plugin and think we're pretty much done and the baby can walk now 👯 
The plugin now uploads only unique files and deletes the old ones, so every time a backup is triggered the code will make sure that only new files and SiteSetting.googledrive_backup_quantity are kept in Drive.
Can you please review?

**Comment by kajatiger** [comment]
💖
