### ISSUE TITLE
first time user / folder issue

### ISSUE THREAD

**Issue by jenni** [berlindiamonds/discourse-googledrive-backup#44]
Hey Kaja,

I think the error eviltrout was having is related to this:

```
    def upload_unique_files
      ([backup] - session.collection_by_title(@folder_name).files).each do |f|
        if f.present?
          full_path = backup.path
          filename = backup.filename
          file = session.upload_from_file(full_path, filename)
          add_to_folder(file)
          session.root_collection.remove(file)
        end
      end
    end
```

`add_to_folder(file)` is the code that contains the **.create_subcollection** . When someone doesn't have a folder created, this operation `([backup] - session.collection_by_title(@folder_name).files) ` throws an error, because there's no collection_by_title. 

Because the method to create the folder depends on the upload_unique_files, the folder is never created without proceeding with the operation first, but the operation depends on the folder creation 😄 

Our folder creation is stuck in a [Catch 22](http://www.urbandictionary.com/define.php?term=Catch%2022)

**Comment by kajatiger** [comment]
aha yes sounds plausible. Doesn't seem like a hard thing to fix it

**Comment by kajatiger** [comment]
https://github.com/berlindiamonds/discourse-sync-to-googledrive/commit/28123b3cbc9cf976e3ac2a85a7a6a18cc15ad2b8
