### ISSUE TITLE
allow downloading files from service account

### ISSUE THREAD

**Issue by jenni** [berlindiamonds/discourse-googledrive-backup#50]
the first step would be the API
list remote files
then for security reasons we don't allow you to just download a backup via the interface
so it would need to email you a link to download it

**Comment by kajatiger** [comment]
in theory the email job already works now and sends an email with the url that has a download link for the file. the problem is that this only works with private google accounts, not for service accounts. the service accounts dont give permission to the download url

**Comment by jenni** [comment]
amazing Kaja great work!
