### ISSUE TITLE
should role be defined to service account?

### ISSUE THREAD

**Issue by jaypatelani** [berlindiamonds/discourse-googledrive-backup#71]
Hi,
Do we need to define role when creating service account or continue with no role? 

Thanks in Advance,
Jay

**Comment by jenni** [comment]
hey @jaypatelani 
not sure how it would affect to go further with no role in the service account, but to make sure it works you should go for:
Service Account > Service Account Admin

**Comment by jaypatelani** [comment]
Thanks you. I will make it Admin for service account for safe side.
